name: release-deb

on:
  push:
    tags:
    - '*'

jobs:
  release_build:
      strategy:
        matrix:
          include:
            - distro: melodic
              ubuntu: bionic
              bloom: python-bloom
            - distro: noetic
              ubuntu: focal
              bloom: python3-bloom
      runs-on: ubuntu-latest
      container:
        image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-ros-${{ matrix.distro }}-ros-base-latest
        #options: -u root  # setup-node requires root access
      steps:
      - uses: actions/checkout@v2
        with:
          path: '.'
      - name: Download packages
        run: |
          sudo apt update
          sudo apt install -y python3-vcstool
          pip3 install setuptools==45.2.0 --no-input
          vcs import --recursive --w 1 < smarc_releases.rosinstall
      - name: Setup environment
        #sudo curl https://raw.githubusercontent.com/smarc-project/rosinstall/master/sources.list.d/smarc-${{ matrix.distro }}-latest.list -o /etc/apt/sources.list.d/smarc-latest.list     
        run: |
          sudo curl https://raw.githubusercontent.com/smarc-project/rosinstall/master/rosdep/50-smarc-${{ matrix.distro }}.list -o /etc/ros/rosdep/sources.list.d/50-smarc.list  
          rosdep update
      - name: Install deps
        run: |
          ls
          sudo apt install -y ${{ matrix.bloom }} fakeroot dpkg-dev debhelper zip
      - name: Build package
        shell: bash
        run: |
          scripts/release_repos.sh ${{ matrix.ubuntu }} ${{ matrix.distro }} release_repos.yaml
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bloom-${{ matrix.distro }}-release-deb.zip
          asset_name: bloom-${{ matrix.distro }}-release-deb.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Debian release generated using bloom"
      - name: Setups deps for EMSDK
        run: |
          sudo apt update
          sudo apt install zip unzip
      - uses: mymindstorm/setup-emsdk@v7      
        with:
          version: '2.0.7'
      - name: Build WASM packages
        shell: bash
        run: |
          scripts/release_repos.sh ${{ matrix.ubuntu }} ${{ matrix.distro }} release_repos_gui.yaml
      - name: Upload WASM binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./bloom-${{ matrix.distro }}-release-deb.zip
          asset_name: bloom-${{ matrix.distro }}-wasm-release-deb.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Debian release generated using bloom"

